sentry_chassis_controller:
  pid:
    p_wheel: 0.5
    i_wheel: 0.005
    d_wheel: 0.0
    i_max_wheel: 1.0
    i_min_wheel: -1.0
    p_: 0.5
    i_: 0.001
    d_: 0.1
    i_max_: 1.0
    i_min_: -1.0
  other:
    use_global_vel_mode : false
    max_linear_accel: 5.0    # 最大线加速度（m/s²）
    max_angular_accel: 5.0   # 最大角加速度（rad/s²）
    cmd_timeout: 5.0
    k1 : 0.1
    k2 : 0.1
    P_max : 100
    wheel_track_ : 0.362
    wheel_base_ : 0.362
    wheel_radius_ : 0.0762



